//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCI.Explorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCI.Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download successful!.
        /// </summary>
        internal static string DownloadSuccessful {
            get {
                return ResourceManager.GetString("DownloadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hactool.exe is missing.
        ///Closing program..
        /// </summary>
        internal static string HacToolMissing {
            get {
                return ResourceManager.GetString("HacToolMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys.txt failed to load.
        ///Please include keys.txt in this location..
        /// </summary>
        internal static string KeysTxtDownloadFailed {
            get {
                return ResourceManager.GetString("KeysTxtDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys.txt is missing.
        ///Do you want to automatically download it now?
        ///
        ///By pressing &apos;Yes&apos; you agree that you own these keys..
        /// </summary>
        internal static string KeysTxtDownloadPrompt {
            get {
                return ResourceManager.GetString("KeysTxtDownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L2VrU0g5Ujh0.
        /// </summary>
        internal static string keyUrlAsBase64String {
            get {
                return ResourceManager.GetString("keyUrlAsBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch XCI (*.xci)|*.xci|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileDialogFilters {
            get {
                return ResourceManager.GetString("OpenFileDialogFilters", resourceCulture);
            }
        }
    }
}
